version: "3.9"

services:
  backend:
    env_file: "./backend/.env"
  build:
    context: ./backend
    dockerfile: ./Dockerfile
  ports:
    - "5000:5000"
  frontend:
    env_file: "./frontend/.env"
    build:
      context: ./frontend
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - "backend"
